# Generated by Django 4.1.7 on 2023-02-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
